catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',
         views.AuthorDetailView.as_view(), name='author-detail'),
]


urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),  # Added for challenge
]


# Add URLConf for librarian to renew a book.
urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]


# Add URLConf to create, update, and delete authors
urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

# Add URLConf to create, update, and delete books
urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]


# Add URLConf to list, view, create, update, and delete genre
urlpatterns += [
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('genre/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
    path('genre/create/', views.GenreCreate.as_view(), name='genre-create'),
    path('genre/<int:pk>/update/', views.GenreUpdate.as_view(), name='genre-update'),
    path('genre/<int:pk>/delete/', views.GenreDelete.as_view(), name='genre-delete'),
]

# Add URLConf to list, view, create, update, and delete languages
urlpatterns += [
    path('languages/', views.LanguageListView.as_view(), name='languages'),
    path('language/<int:pk>', views.LanguageDetailView.as_view(),
         name='language-detail'),
    path('language/create/', views.LanguageCreate.as_view(), name='language-create'),
    path('language/<int:pk>/update/',
         views.LanguageUpdate.as_view(), name='language-update'),
    path('language/<int:pk>/delete/',
         views.LanguageDelete.as_view(), name='language-delete'),
]

# Add URLConf to list, view, create, update, and delete bookinstances
urlpatterns += [
    path('bookinstances/', views.BookInstanceListView.as_view(), name='bookinstances'),
    path('bookinstance/<uuid:pk>', views.BookInstanceDetailView.as_view(),
         name='bookinstance-detail'),
    path('bookinstance/create/', views.BookInstanceCreate.as_view(),
         name='bookinstance-create'),
    path('bookinstance/<uuid:pk>/update/',
         views.BookInstanceUpdate.as_view(), name='bookinstance-update'),
    path('bookinstance/<uuid:pk>/delete/',
         views.BookInstanceDelete.as_view(), name='bookinstance-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]



#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        unique=True,
        verbose_name = u'Название жанра',
        help_text="Укажите жанр книги (например, научная фантастика, французская поэзия и т.д.)."
    )
    class Meta:
        verbose_name = u'Жанр'
        verbose_name_plural = u'Жанры'

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('genre-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            unique=True,
                            verbose_name = u'Язык',
                            help_text="Введите язык книги (например, английский, французский, японский и т.д.).")
    class Meta:
        verbose_name = u'Язык'
        verbose_name_plural = u'Языки'
    def get_absolute_url(self):
        """Returns the url to access a particular language instance."""
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200, verbose_name = u'Название книги')
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True,verbose_name = u'Автор')
    # Foreign Key used because book can only have one author, but authors can have multiple books.
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(
        max_length=1000, help_text="Введите краткое описание книги", verbose_name = u'Краткое содержание')
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 символов <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text="Выберите жанр для этой книги",verbose_name = u'Жанр')
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True, verbose_name = u'Язык')

    class Meta:
        ordering = ['title', 'author']
        verbose_name = u'Книга'
        verbose_name_plural = u'Книги'

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book record."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


import uuid  # Required for unique book instances
from datetime import date

from django.conf import settings  # Required to assign User as a borrower


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Уникальный идентификатор для этой конкретной книги во всей библиотеке")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True,verbose_name = u'Книга')
    imprint = models.CharField(max_length=200,verbose_name = u'Сведения о копии')
    due_back = models.DateField(null=True, blank=True,verbose_name = u'Дата возвврата')
    borrower = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,verbose_name = u'Читатель')

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('d', 'На обслуживание'),
        ('o', 'Зарезервирована пользователем'),
        ('a', 'Доступна'),
        ('r', 'Зарезервирована'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Наличие свободных книг',
        verbose_name = u'Статус')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
        verbose_name = u'Бронирование книг'
        verbose_name_plural = u'Бронирование книг'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('bookinstance-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100,verbose_name = u'Имя')
    last_name = models.CharField(max_length=100,verbose_name = u'Фамилия')
    date_of_birth = models.DateField(null=True, blank=True, verbose_name = 'Дата рождения')
    date_of_death = models.DateField(null=True, blank=True, verbose_name = 'Дата смерти')

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = u'Автор'
        verbose_name_plural = u'Авторы'

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime  # for checking renewal date range.

from django import forms


class RenewBookForm(forms.Form):
    """Form for a librarian to renew books."""
    renewal_date = forms.DateField(
            help_text="Введите дату от текущего момента до 4 недель (по умолчанию 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Недействительная дата - продление в прошлом'))
        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Недействительная дата - продление более чем на 4 недели вперед'))

        # Remember to always return the cleaned data.
        return data

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h1>Удалить автора: {{ author }}</h1>

    {% if author.book_set.all %}

    <p>Вы не сможете удалить этого автора до тех пор, пока не будут удалены все его книги:</p>
    <ul>
      {% for book in author.book_set.all %}
      <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
      {% endfor %}
    </ul>

    {% else %}
    <p>Вы уверены, что хотите удалить автора?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" action="" value="Да, удалить">
    </form>
    {% endif %}
  </div>
</div>


{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="Выполнить">
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список авторов</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>Доступных авторов нет.</p>
{% endif %}
        
        
        
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Название: {{ book.title }}</h1>

<p><strong>Автор:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
<p><strong>Аннотация:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Язык:</strong> {{ book.language }}</p>
<p><strong>Жанр:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Экземпляры</h4>

{% for copy in book.bookinstance_set.all %}
  <hr>
  <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
  {% if copy.status != 'a' %}<p><strong>Будет возвращен:</strong> {{copy.due_back}}</p>{% endif %}
  <p><strong>Сведения об экземпляре:</strong> {{copy.imprint}}</p>
  <p class="text-muted"><strong>Id:</strong> <a href="{{ copy.get_absolute_url }}">{{copy.id}}</a></p>
{% empty %}
  <p>В библиотеке нет экземпляров этой книги.</p>
{% endfor %}
</div>
{% endblock %}


{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_book or perms.catalog.delete_book %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_book %}
      <li><a href="{% url 'book-update' book.id %}">Изменить книгу</a></li>
    {% endif %}
    {% if not book.bookinstance_set.all and perms.catalog.delete_book %}
      <li><a href="{% url 'book-delete' book.id %}">Удалить книгу</a></li>
    {% endif %}
    </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="Выполнить">
    
</form>
{% endblock %}

catalog/templates/catalog/bookinstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удалить экземпляр книги: {{ bookinstance }}</h1>

<p>Вы уверены, что хотите удалить эту копию книги?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Да, удалить.">
</form>

{% endblock %}

catalog/templates/catalog/bookinstance_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Брони книг: {{ bookinstance.book.title }}</h1>

<p><strong>Автор:</strong> <a href="{{ bookinstance.book.author.get_absolute_url }}">{{ bookinstance.book.author }}</a></p>

<p><strong>Сведения о копии:</strong> {{ bookinstance.imprint }}</p>
<p><strong>Статус:</strong> {{ bookinstance.get_status_display }} {% if bookinstance.status != 'a' %} (Due: {{bookinstance.due_back}}){% endif %}</p>

<hr>
<ul>
  <li>
    <a href="{{ bookinstance.book.get_absolute_url }}">Все экземпляры</a></p>
  </li>
</ul>
{% endblock %}


{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_bookinstance or perms.catalog.delete_bookinstance %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_bookinstance %}
      <li><a href="{% url 'bookinstance-update' bookinstance.id %}">Изменить брони книг</a></li>
    {% endif %}
    {% if perms.catalog.delete_bookinstance %}
      <li><a href="{% url 'bookinstance-delete' bookinstance.id %}">Удалить брони книг</a></li>
    {% endif %}
  </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/bookinstance_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
        {{ form|crispy}}
    <input type="submit" class="btn btn-success" value="Обновить">

</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Забронированные книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет забронированных книг</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/genre_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удалить жанр: {{ genre }}</h1>

<p>Вы уверены, что хотите удалить этот жанр?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Да, удалить.">
</form>

{% endblock %}

catalog/templates/catalog/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Жанр: {{ genre.name }}</h1>

<div style="margin-left:20px;margin-top:20px">
<h4>Книги в данном жанре</h4>

<ul>
  {% for copy in genre.book_set.all %}
  <li>
    <a href="{{ copy.get_absolute_url }}">{{ copy.title }}</a> ({{copy.author}})
  </li>
  {% empty %}
  <li>Нет книг в этом жанре.</li>
  {% endfor %}
</ul>

{% endblock %}


{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_genre or perms.catalog.delete_genre %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_genre %}
    <li><a href="{% url 'genre-update' genre.id %}">Изменить жанр</a></li>
    {% endif %}
    {% if not genre.book_set.all and perms.catalog.delete_genre %}
      <li><a href="{% url 'genre-delete' genre.id %}">Удалить жанр</a></li>
    {% endif %}
    </ul>
  {% endif %}

{% endblock %}

catalog/templates/catalog/language_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удалить язык: {{ language }}</h1>

<p>Вы уверены, что хотите удалить этот язык?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Да, удалить.">
</form>

{% endblock %}

catalog/templates/catalog/language_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success" value="Выполнить">

</form>
{% endblock %}

catalog/templates/catalog/language_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Список языков</h1>

<ul>
  {% for language in language_list %}
  <li>
    <a href="{{ language.get_absolute_url }}">{{ language }}</a>
  </li>
  {% empty %}
  <li>Здесь нет доступных языков.</li>
  {% endfor %}
</ul>

{% endblock %}